#!/usr/bin/env bash
# BCSE402L - Big Data Analytics (TH)
# DA-2 artefact: cluster bring-up for the pseudo-distributed setup.
#
# Idempotent: safe to re-run. It writes the environment file, installs the
# configuration XMLs from code/config into the Hadoop and Hive conf
# directories, formats the NameNode only once, and starts HDFS + YARN.
#
# Usage:  source code/scripts/00_setup_env.sh   # env vars only
#         bash   code/scripts/00_setup_env.sh   # full setup
set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_DIR="$PROJECT_DIR/code/config"
DATA_ROOT="/Users/abhishek/bd-hadoop-data"

BREW_PREFIX="$(brew --prefix)"
HADOOP_HOME="$BREW_PREFIX/opt/hadoop/libexec"
HIVE_HOME="$BREW_PREFIX/opt/hive"
SPARK_HOME="$BREW_PREFIX/opt/apache-spark/libexec"

# A single JDK (21) is used for Hadoop, Hive and Spark. Hive 4.2.1's classes
# are compiled for class-file version 65 (JDK 21) and its CLI delegates to
# `hadoop jar`, so whichever JDK Hadoop uses is also the JDK Hive's beeline
# runs on. Hadoop 3.5.0 supports JDK 21, so one JDK keeps all three consistent
# and avoids UnsupportedClassVersionError.
JAVA_HOME_17="$BREW_PREFIX/opt/openjdk@17"
JAVA_HOME_21="$BREW_PREFIX/opt/openjdk@21"

# Homebrew paths differ between the two supported installs; fall back to the
# libexec flavour if the direct opt link is absent.
[ -d "$SPARK_HOME" ] || SPARK_HOME="$BREW_PREFIX/opt/apache-spark"
[ -d "$HIVE_HOME/conf" ] || HIVE_HOME="$BREW_PREFIX/opt/hive/libexec"

export JAVA_HOME="$JAVA_HOME_21"
export HADOOP_HOME
export HADOOP_CONF_DIR="$HADOOP_HOME/etc/hadoop"
export HIVE_HOME
export SPARK_HOME
export HADOOP_MAPRED_HOME="$HADOOP_HOME"
export YARN_HOME="$HADOOP_HOME"
export PATH="$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HIVE_HOME/bin:$SPARK_HOME/bin:$PATH"
export HADOOP_OPTS="-Djava.awt.headless=true"
export HADOOP_CLIENT_OPTS="-Xmx1g"

# Hadoop, Hive and the Kryo serializer traverse JDK internals reflectively,
# while JDK 17+ enforces strong encapsulation. The required --add-opens flags
# live in one file and are applied to every JVM that needs them: the daemons,
# the Hive client, and the MapReduce task containers.
OPENS_FILE="$CONFIG_DIR/jdk-opens.txt"
JDK17_OPENS_STR="$(grep -v '^[[:space:]]*#' "$OPENS_FILE" | tr '\n' ' ' | sed 's/[[:space:]]*$//')"

# ---------------------------------------------------------------- env file
ENV_FILE="$PROJECT_DIR/code/scripts/env.sh"
cat > "$ENV_FILE" <<EOF
# Generated by 00_setup_env.sh - source this before running cluster commands.
export JAVA_HOME="$JAVA_HOME"
# Hadoop and Hive reach into JDK internals by reflection. JDK 17 and later
# enforce strong encapsulation, so these packages must be opened explicitly or
# the daemons and clients abort with InaccessibleObjectException.
export HADOOP_HOME="$HADOOP_HOME"
export HADOOP_CONF_DIR="$HADOOP_CONF_DIR"
export HIVE_HOME="$HIVE_HOME"
export SPARK_HOME="$SPARK_HOME"
export HADOOP_MAPRED_HOME="$HADOOP_MAPRED_HOME"
export YARN_HOME="$YARN_HOME"
export HADOOP_OPTS="$HADOOP_OPTS"
export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS"
export PROJECT_DIR="$PROJECT_DIR"
export PATH="\$JAVA_HOME/bin:\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin:\$HIVE_HOME/bin:\$SPARK_HOME/bin:\$PATH"
EOF

if [ -z "${BASH_SOURCE[0]:-}" ] || [[ "${BASH_SOURCE[0]}" == "$0" ]] || [ "$0" = "bash" ]; then
    echo "=== ENVIRONMENT ==="
    echo "JAVA_HOME   $JAVA_HOME   ($("$JAVA_HOME/bin/java" -version 2>&1 | head -1))"
    echo "HADOOP_HOME $HADOOP_HOME"
    echo "HIVE_HOME   $HIVE_HOME"
    echo "SPARK_HOME  $SPARK_HOME"
    echo "env file    $ENV_FILE"
fi

# ------------------------------------------------- install configuration XMLs
# mapred-site.xml carries a generated block of JDK module-access flags, so the
# three java.opts properties are rewritten from jdk-opens.txt on every run
# rather than being duplicated by hand in the XML.
inject_mapred_jdk_opens() {
    local src="$CONFIG_DIR/mapred-site.xml"
    local dst="$HADOOP_CONF_DIR/mapred-site.xml"
    python3 - "$src" "$dst" "$JDK17_OPENS_STR" <<'PY'
import sys
src, dst, opens = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(src).read()
props = """  <!-- JDK-OPENS:START -->
  <property>
    <name>mapreduce.map.java.opts</name>
    <value>-Xmx800m {opens}</value>
  </property>
  <property>
    <name>mapreduce.reduce.java.opts</name>
    <value>-Xmx800m {opens}</value>
  </property>
  <property>
    <name>yarn.app.mapreduce.am.command-opts</name>
    <value>-Xmx1024m {opens}</value>
  </property>
  <!-- JDK-OPENS:END -->""".format(opens=opens)

start = text.index("<!-- JDK-OPENS:START -->")
end = text.index("<!-- JDK-OPENS:END -->") + len("<!-- JDK-OPENS:END -->")
open(dst, "w").write(text[:start] + props + text[end:])
PY
}

install_configs() {
    echo
    echo "=== INSTALLING CONFIGURATION ==="
    for f in core-site.xml hdfs-site.xml yarn-site.xml; do
        cp "$CONFIG_DIR/$f" "$HADOOP_CONF_DIR/$f"
        echo "  $HADOOP_CONF_DIR/$f"
    done
    inject_mapred_jdk_opens
    echo "  $HADOOP_CONF_DIR/mapred-site.xml (with JDK module-access flags)"
    # Hive reads its own conf dir; the Hadoop XMLs are also copied there so
    # the Hive client resolves the same filesystem and YARN settings.
    HIVE_CONF="$HIVE_HOME/conf"
    mkdir -p "$HIVE_CONF"
    cp "$CONFIG_DIR/hive-site.xml" "$HIVE_CONF/hive-site.xml"
    echo "  $HIVE_CONF/hive-site.xml"
    for f in core-site.xml hdfs-site.xml mapred-site.xml yarn-site.xml; do
        cp "$HADOOP_CONF_DIR/$f" "$HIVE_CONF/$f"
        echo "  $HIVE_CONF/$f"
    done

    # Spark resolves the same cluster configuration.
    SPARK_CONF="$SPARK_HOME/conf"
    mkdir -p "$SPARK_CONF"
    for f in core-site.xml hdfs-site.xml yarn-site.xml; do
        cp "$HADOOP_CONF_DIR/$f" "$SPARK_CONF/$f"
    done
    cp "$CONFIG_DIR/hive-site.xml" "$SPARK_CONF/hive-site.xml"
    echo "  $SPARK_CONF/{core-site,hdfs-site,yarn-site,hive-site}.xml"
}

# Hadoop on JDK 17 needs these module opens for its reflective access; the
# entries go into hadoop-env.sh which the launch scripts source.
patch_hadoop_env() {
    local envfile="$HADOOP_CONF_DIR/hadoop-env.sh"
    [ -f "$envfile" ] || return 0
    if ! grep -q "BD_PROJECT_JAVA_HOME" "$envfile"; then
        cat >> "$envfile" <<EOF

# --- added for BCSE402L DA-2 (BD_PROJECT_JAVA_HOME) ---
export JAVA_HOME="$JAVA_HOME"
# One predictable place for daemon logs, so the report can cite them.
export HADOOP_LOG_DIR="$DATA_ROOT/logs"
export YARN_LOG_DIR="$DATA_ROOT/logs"
# Hadoop reaches into JDK internals via reflection; JDK 17 enforces strong
# encapsulation, so these packages must be opened explicitly. Without them the
# daemons and the client commands abort with InaccessibleObjectException.
JDK17_OPENS="$JDK17_OPENS_STR"
export HDFS_NAMENODE_OPTS="-Djava.awt.headless=true \$JDK17_OPENS"
export HDFS_DATANODE_OPTS="-Djava.awt.headless=true \$JDK17_OPENS"
export HDFS_SECONDARYNAMENODE_OPTS="-Djava.awt.headless=true \$JDK17_OPENS"
export YARN_RESOURCEMANAGER_OPTS="-Djava.awt.headless=true \$JDK17_OPENS"
export YARN_NODEMANAGER_OPTS="-Djava.awt.headless=true \$JDK17_OPENS"
export HADOOP_OPTS="-Djava.awt.headless=true \$JDK17_OPENS"
export HADOOP_CLIENT_OPTS="\$JDK17_OPENS"
EOF
        echo "  patched $envfile"
    fi
}

# ------------------------------------------------------------------ format
format_namenode() {
    if [ -d "$DATA_ROOT/dfs/name/current" ]; then
        echo
        echo "NameNode already formatted ($DATA_ROOT/dfs/name/current exists) - skipping"
        return 0
    fi
    echo
    echo "=== FORMATTING NAMENODE ==="
    mkdir -p "$DATA_ROOT"/{dfs/name,dfs/data,dfs/namesecondary,tmp,hive,yarn/local,yarn/container-logs}
    hdfs namenode -format -force -nonInteractive 2>&1 | tail -8
}

# ------------------------------------------------------------------- start
# Daemons are started individually with `--daemon start` rather than through
# start-dfs.sh / start-yarn.sh. Those wrapper scripts launch daemons over ssh,
# which on a fresh macOS account prompts for a password and hangs; starting
# them locally is equivalent on a single machine and fully non-interactive.
start_daemon() {
    local label="$1"; shift
    local logfile="/tmp/bd-${label}.out"
    # $* is intentionally unquoted: the caller passes the command and its
    # arguments as separate shell words.
    if $* > "$logfile" 2>&1; then
        echo "  started $label"
    else
        echo "  FAILED to start $label:"
        sed 's/^/    /' "$logfile" | tail -8
    fi
}

wait_for_port() {
    local port="$1" name="$2"
    for _ in $(seq 1 20); do
        if nc -z -G 2 localhost "$port" >/dev/null 2>&1; then
            echo "  $name listening on $port"
            return 0
        fi
        sleep 2
    done
    echo "  $name NOT listening on $port"
    return 1
}

start_cluster() {
    echo
    echo "=== STARTING HDFS DAEMONS ==="
    start_daemon namenode hdfs --daemon start namenode
    wait_for_port 9000 "NameNode (RPC)"
    wait_for_port 9870 "NameNode (web UI)"
    start_daemon datanode hdfs --daemon start datanode
    wait_for_port 9864 "DataNode (web UI)"

    echo
    echo "=== STARTING YARN DAEMONS ==="
    start_daemon resourcemanager yarn --daemon start resourcemanager
    wait_for_port 8032 "ResourceManager"
    start_daemon nodemanager yarn --daemon start nodemanager
    wait_for_port 8041 "NodeManager"

    echo
    echo "=== CLUSTER REPORT ==="
    hdfs dfsadmin -report 2>&1 | head -18
    echo
    echo "=== YARN NODES ==="
    yarn node -list 2>&1 | tail -5
}

# Hive 4.2.1 is built against JDK 21 (its Homebrew dependency), while Hadoop
# runs on JDK 17. The two are separate JVMs, so each gets its own JAVA_HOME.
patch_hive_env() {
    local hiveenv="$HIVE_HOME/conf/hive-env.sh"
    cat > "$hiveenv" <<EOF
# Generated for BCSE402L DA-2.
# One JDK (21) is shared by Hadoop, Hive and Spark; see 00_setup_env.sh.
export JAVA_HOME="$JAVA_HOME_21"
export HADOOP_HOME="$HADOOP_HOME"
export HIVE_CONF_DIR="$HIVE_HOME/conf"
export HIVE_AUX_JARS_PATH="$HIVE_HOME/lib"
export HADOOP_HEAPSIZE=1024
# JDK 17+ enforces strong encapsulation; Hive and its dependencies traverse
# JDK internals reflectively, so those packages must be opened explicitly.
export HADOOP_CLIENT_OPTS="\$HADOOP_CLIENT_OPTS $JDK17_OPENS_STR"
export HIVE_OPTS="\$HIVE_OPTS $JDK17_OPENS_STR"
EOF
    echo "  wrote $hiveenv"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    install_configs
    patch_hadoop_env
    patch_hive_env
    if [ "${1:-all}" == "configs" ]; then
        echo
        echo "config-only run: daemons left untouched"
        exit 0
    fi
    format_namenode
    start_cluster
    echo
    echo "=== JAVA PROCESSES ==="
    jps 2>/dev/null | grep -Ev "^\s*$" || true
fi
