# Generated by 00_setup_env.sh - source this before running cluster commands.
export JAVA_HOME="/opt/homebrew/opt/openjdk@21"
# Hadoop and Hive reach into JDK internals by reflection. JDK 17 and later
# enforce strong encapsulation, so these packages must be opened explicitly or
# the daemons and clients abort with InaccessibleObjectException.
export HADOOP_HOME="/opt/homebrew/opt/hadoop/libexec"
export HADOOP_CONF_DIR="/opt/homebrew/opt/hadoop/libexec/etc/hadoop"
export HIVE_HOME="/opt/homebrew/opt/hive/libexec"
export SPARK_HOME="/opt/homebrew/opt/apache-spark/libexec"
export HADOOP_MAPRED_HOME="/opt/homebrew/opt/hadoop/libexec"
export YARN_HOME="/opt/homebrew/opt/hadoop/libexec"
export HADOOP_OPTS="-Djava.awt.headless=true"
export HADOOP_CLIENT_OPTS="-Xmx1g"
export PROJECT_DIR="/Users/abhishek/Documents/projects/BD PROJECT/DA2"
export PATH="$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HIVE_HOME/bin:$SPARK_HOME/bin:$PATH"
